-- DropForeignKey
ALTER TABLE "Descriptions" DROP CONSTRAINT "Descriptions_commentId_fkey";

-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "username" SET DATA TYPE VARCHAR,
ALTER COLUMN "password" SET DATA TYPE VARCHAR,
ALTER COLUMN "email" SET DATA TYPE VARCHAR,
ALTER COLUMN "role" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Card" ALTER COLUMN "title" SET DATA TYPE VARCHAR,
ALTER COLUMN "description_big" SET DATA TYPE VARCHAR,
ALTER COLUMN "description1" SET DATA TYPE VARCHAR,
ALTER COLUMN "description2" SET DATA TYPE VARCHAR,
ALTER COLUMN "description3" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "City" ALTER COLUMN "name" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "author" SET DATA TYPE VARCHAR,
ALTER COLUMN "photo" SET DATA TYPE VARCHAR,
ALTER COLUMN "comment" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Conditions" ALTER COLUMN "condition" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Country" ALTER COLUMN "name" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Descriptions" ALTER COLUMN "destination" SET DATA TYPE VARCHAR,
ALTER COLUMN "accommodation" SET DATA TYPE VARCHAR,
ALTER COLUMN "activities" SET DATA TYPE VARCHAR,
ALTER COLUMN "commentId" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Facilities" ALTER COLUMN "facility" SET DATA TYPE VARCHAR,
ALTER COLUMN "icon" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Hotel" ALTER COLUMN "name" SET DATA TYPE VARCHAR,
ALTER COLUMN "movie" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "HotelImages" ALTER COLUMN "path" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "News" ALTER COLUMN "title" SET DATA TYPE VARCHAR,
ALTER COLUMN "banner" SET DATA TYPE VARCHAR,
ALTER COLUMN "author" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Ratings" ALTER COLUMN "rating" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Slider" ALTER COLUMN "title" SET DATA TYPE VARCHAR,
ALTER COLUMN "information" SET DATA TYPE VARCHAR,
ALTER COLUMN "comment" SET DATA TYPE VARCHAR,
ALTER COLUMN "author" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Sports" ALTER COLUMN "sport" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "Team" ALTER COLUMN "name" SET DATA TYPE VARCHAR;

-- AlterTable
ALTER TABLE "TravelTime" ALTER COLUMN "travel_time" SET DATA TYPE VARCHAR;

-- AddForeignKey
ALTER TABLE "Descriptions" ADD CONSTRAINT "Descriptions_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "Comment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
